### ISSUE TITLE
Error: 'NoneType' object has no attribute 'group'

### ISSUE THREAD

**Issue by la3rence** [yanglbme/v2ex-action#4]
Hey, thanks to the gh-action.

There's a problem when I using it to send Dingtalk message and this is the action log:

```log
Run yanglbme/v2ex-action@main
/usr/bin/docker run --name e4202e3af594374deab808e7a38f058321_d8112c --label 5588e4 --workdir /github/workspace --rm -e INPUT_WEBHOOK -e INPUT_SECRET -e INPUT_COUNT -e HOME -e GITHUB_JOB -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_REPOSITORY_OWNER -e GITHUB_RUN_ID -e GITHUB_RUN_NUMBER -e GITHUB_RETENTION_DAYS -e GITHUB_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_SERVER_URL -e GITHUB_API_URL -e GITHUB_GRAPHQL_URL -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e GITHUB_ACTION_REPOSITORY -e GITHUB_ACTION_REF -e GITHUB_PATH -e GITHUB_ENV -e RUNNER_OS -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -e ACTIONS_RUNTIME_URL -e ACTIONS_RUNTIME_TOKEN -e ACTIONS_CACHE_URL -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/work/V2exHot/V2exHot":"/github/workspace" 5588e4:202e3af594374deab808e7a38f058321
Error: 'NoneType' object has no attribute 'group'
```

You can check it in my repo's action page: https://github.com/Lonor/V2exHot/runs/1976959865

**Comment by yanglbme** [comment]
Yeah, the V2EX Action run failed since 11:46 am, and I've received many warning emails from GitHub. https://github.com/yanglbme/reading/actions?page=2

![image](https://user-images.githubusercontent.com/21008209/109119422-a05e0400-777f-11eb-844c-3feb76c30ea8.png)

![image](https://user-images.githubusercontent.com/21008209/109118749-adc6be80-777e-11eb-892c-c9137f46bb9d.png)

![image](https://user-images.githubusercontent.com/21008209/109118827-cc2cba00-777e-11eb-94bd-38b5e9550c9e.png)


I'll fix the problem today.  Thanks for your feedback.

**Comment by la3rence** [comment]
Problem solved. Thank you!
